stages:
  - build
  - static code
  - test

image: python:3.8.12

before_script:
  - python -V
  - python -m pip install --upgrade pip
  - python -m pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
  
.build: &build
  - python -m pip install .

build:
  stage: build
  script: *build

flake8:
  stage: static code
  script:
    - *build
    - python -m pip install flake8
    - flake8 pysniffwave

mypy:
  stage: static code
  script:
    - *build
    - python -m pip install mypy
    - mypy --install-type --non-interactive --ignore-missing-imports pysniffwave

pytest:
  stage: test
  script:
    - *build
    - python -m pip install pytest pytest-cov pytest-socket
    - pytest tests/* --log-level=DEBUG
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
